'use strict';
(()=>{
  const $=id=>document.getElementById(id),X=window.Xuanqi;
  const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const form=$('oracle-form'),dialog=$('methods-dialog');let previousFocus=null,lastLunarMinute='',lastResult=null;
  document.querySelectorAll('[data-open-methods]').forEach(b=>b.addEventListener('click',()=>{previousFocus=document.activeElement;dialog.showModal();}));
  $('close-methods').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>previousFocus?.focus());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
  const error=message=>{$('form-error').textContent=message;$('form-error').hidden=!message;};
  if(!X||!window.Solar){error('历法未能载入，请刷新页面后重试。');$('cast-button').disabled=true;return;}
  function clock(){try{const now=new Date(),p=X.beijingParts(now),time=X.formatParts(p);$('current-time').textContent=time;$('current-time').dateTime=now.toISOString();if(time.slice(0,16)!==lastLunarMinute){lastLunarMinute=time.slice(0,16);const l=X.solarAt(now).getLunar(),hour=X.ZHI[Math.floor((p.hour+1)/2)%12];$('lunar-time').textContent=`${l.toString()} · ${hour}时 · UTC+8`;}}catch{error('无法读取当前时间，请检查设备时钟。');}}
  clock();setInterval(clock,1000);
  const todayParts=(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;})();$('birth-date').max=todayParts;
  $('question').addEventListener('input',()=>{$('character-count').textContent=`${$('question').value.length} / 300`;});
  $('unknown-time').addEventListener('change',()=>{const unknown=$('unknown-time').checked;$('birth-time').disabled=unknown;$('birth-time').required=!unknown;});
  function toggleCustom(){const custom=$('birth-zone').value==='custom';$('custom-zone-field').hidden=!custom;$('custom-zone').required=custom;}
  $('birth-zone').addEventListener('change',()=>{toggleCustom();$('zone-help').textContent='将按所选时区（含夏令时）换算为 UTC+8 北京时间，不校正真太阳时。';});
  if(Intl.supportedValuesOf){try{const frag=document.createDocumentFragment();Intl.supportedValuesOf('timeZone').forEach(zone=>{const opt=document.createElement('option');opt.value=zone;frag.append(opt);});$('all-zones').append(frag);}catch{}}
  const cityZones=[[/纽约|new\s*york|波士顿|boston|华盛顿|washington|迈阿密|miami/i,'America/New_York'],[/洛杉矶|los\s*angeles|旧金山|san\s*francisco|西雅图|seattle|伯克利|berkeley/i,'America/Los_Angeles'],[/芝加哥|chicago|达拉斯|dallas|休斯顿|houston/i,'America/Chicago'],[/丹佛|denver/i,'America/Denver'],[/凤凰城|phoenix/i,'America/Phoenix'],[/多伦多|toronto|蒙特利尔|montreal/i,'America/Toronto'],[/温哥华|vancouver/i,'America/Vancouver'],[/伦敦|london|英国|liverpool|manchester/i,'Europe/London'],[/巴黎|paris/i,'Europe/Paris'],[/柏林|berlin|慕尼黑|munich/i,'Europe/Berlin'],[/斯德哥尔摩|stockholm|瑞典/i,'Europe/Stockholm'],[/新加坡|singapore/i,'Asia/Singapore'],[/东京|大阪|日本|tokyo|osaka/i,'Asia/Tokyo'],[/首尔|韩国|seoul/i,'Asia/Seoul'],[/曼谷|泰国|bangkok/i,'Asia/Bangkok'],[/孟买|新德里|印度|mumbai|delhi/i,'Asia/Kolkata'],[/迪拜|dubai/i,'Asia/Dubai'],[/悉尼|sydney|墨尔本|melbourne/i,'Australia/Sydney'],[/珀斯|perth/i,'Australia/Perth'],[/奥克兰|auckland/i,'Pacific/Auckland'],[/香港|hong\s*kong/i,'Asia/Hong_Kong'],[/台北|台湾|taipei|taiwan/i,'Asia/Taipei'],[/约翰内斯堡|johannesburg/i,'Africa/Johannesburg'],[/中国|上海|北京|天津|重庆|广州|深圳|成都|南京|杭州|苏州|西安|武汉|青岛|济南|合肥|长沙|南昌|福州|厦门|沈阳|大连|哈尔滨|长春|郑州|石家庄|昆明|贵阳|南宁|海口|兰州|西宁|银川|太原|乌鲁木齐|拉萨|呼和浩特|宁波|无锡|佛山|东莞|珠海|中国|china|shanghai|beijing|guangzhou|shenzhen|chengdu/i,'Asia/Shanghai']];
  $('birth-place').addEventListener('change',()=>{const match=cityZones.find(([pattern])=>pattern.test($('birth-place').value));if(match){$('birth-zone').value=match[1];toggleCustom();$('zone-help').textContent=`已匹配 ${$('birth-zone').selectedOptions[0].textContent}；请核对，出生时间将换算为 UTC+8 北京时间。`;}else{$('zone-help').textContent='未自动识别此地点的时区，请手动选择对应时区。出生地点用于确定当地时间。';}});
  function getInput(){return {question:$('question').value.trim(),topic:new FormData(form).get('topic'),birthDate:$('birth-date').value,birthTime:$('birth-time').value,birthPlace:$('birth-place').value.trim(),birthZone:$('birth-zone').value==='custom'?$('custom-zone').value.trim():$('birth-zone').value,unknownTime:$('unknown-time').checked};}
  function hexView(hex,moving,label){return `<div><div class="hexagram" role="img" aria-label="${escape(hex.longName)}，自下至上为${hex.bits.map((v,i)=>(v?'阳':'阴')+(moving===i+1?'动爻':'')).join('、')}">${[...hex.bits].reverse().map((v,i)=>`<div class="yao${moving===6-i?' moving':''}"><i></i>${v?'':'<i></i>'}</div>`).join('')}</div><div class="hex-label">${escape(hex.longName)}<small>${label}</small></div></div>`;}
  function render(r,input){
    $('question-recap').textContent=input.question;$('cast-time').textContent=`起课于 ${r.beijing} · 北京`;$('classical-reading').textContent=r.reading.classical;$('translation').textContent=r.reading.translation;$('practical').textContent=r.reading.practical;
    $('small-chart').innerHTML=`<div class="palace-result"><span class="palace-name">${r.small.name}</span><p>${r.reading.rhythm}<br>农历${r.month}月${r.day}日 · ${r.hour}时</p></div><div class="palaces">${X.PALACES.map((name,i)=>`<div class="palace${i===r.small.index?' selected':''}"${i===r.small.index?' aria-label="本次落宫 '+name+'"':''}>${name}</div>`).join('')}</div><p class="chart-note">月落${r.small.monthPalace}，日落${r.small.dayPalace}，时落${r.small.name}。${r.leap?'闰月按本月数起算。':''}</p>`;
    $('liuren-chart').innerHTML=`<div class="lessons">${r.six.lessons.map((l,i)=>`<div class="lesson"><small>第${['一','二','三','四'][i]}课</small><strong>${l.upper}</strong><strong>${l.lower}</strong><span>${X.RELATION_TEXT[l.relation]}</span></div>`).join('')}</div><p class="plate-summary">${r.six.day}日 · ${r.six.generalName}${r.six.general}将 · 加${r.hour}时</p><p class="chart-note">${r.six.qi}中气后用${r.six.general}将；日干寄${r.six.host}。本版排天地盘、四课，不含三传与天将。</p>`;
    $('meihua-chart').innerHTML=`<div class="hexa-pair">${hexView(r.meihua.original,r.meihua.moving,'本卦 · '+['初','二','三','四','五','上'][r.meihua.moving-1]+'爻动')}<span class="hex-transition">之</span>${hexView(r.meihua.changed,0,'变卦')}</div><p class="plate-summary">体${r.meihua.body.name}·${r.meihua.body.element} / 用${r.meihua.use.name}·${r.meihua.use.element} / ${r.reading.meiName}</p><p class="chart-note">${r.reading.meiText}</p>`;
    $('birth-caption').textContent=`${input.birthPlace} · ${input.birthZone}\n${input.birthDate} ${input.unknownTime?'时辰不详':input.birthTime}（当地）\n${r.birth.unknownTime?'年、月柱仅显示全天不变的值。':`换算北京：${r.birth.beijing}`}${r.birth.ambiguous?'；此时间在夏令时回拨中出现两次，本次采用较早的一次。':''}`;
    $('birth-chart').innerHTML=`<div class="pillars">${r.birth.pillars.map(p=>`<div class="pillar"><div class="pillar-label">${p.label}</div><strong>${p.value}</strong><small>${p.elements} · ${p.nayin}</small></div>`).join('')}</div><p class="element-note">${r.birth.dayElement?`日主 ${r.birth.dayStem}${r.birth.dayElement} · ${X.ELEMENT_COPY[r.birth.dayElement]}这里只展示表层干支五行，不据此判断五行旺衰或喜忌。`:'出生时辰不详，日柱、时柱及日主留空；节气交界日的年柱或月柱也可能无法确定。'}</p>`;
    $('calculation-details').innerHTML=`<p><b>统一时刻：</b>${r.beijing}（UTC+8），${r.lunar}，${r.hour}时。时钟来自设备；点击起课时固定本次时间。</p><p><b>小六壬：</b>月宫序号 = (${r.month} − 1) mod 6 = ${r.small.monthIndex}；日宫序号 = (${r.small.monthIndex} + ${r.day} − 1) mod 6 = ${r.small.dayIndex}；时宫序号 = (${r.small.dayIndex} + ${r.hourNumber} − 1) mod 6 = ${r.small.index}。序号从大安 = 0 起算。</p><p><b>六壬：</b>最近中气为${r.six.qi}（${r.six.qiDate} 北京时间），用${r.six.general}将；将${r.six.general}置于地盘${r.hour}位，其余地支顺排。四课自第一课起：日干上神、干上神之上神、日支上神、支上神之上神。</p><div class="earth-grid" aria-label="天地盘对照，上方为天盘，下方为地盘">${X.ZHI.map((z,i)=>`<div class="earth-cell"><b>${r.six.heaven[i]}</b><span>${z}</span></div>`).join('')}</div><p class="chart-note">上行为天盘，下行为地盘；本版未纳入三传、十二天将和九宗门。</p><p><b>梅花易数：</b>农历年支数 ${r.yearNumber} + 月数 ${r.month} + 日数 ${r.day} = ${r.meihua.subtotal}；除 8 余 ${r.meihua.subtotal%8}，得上卦${X.TRIGRAMS[r.meihua.original.upper].name}。再加时支数 ${r.hourNumber} = ${r.meihua.total}；除 8 余 ${r.meihua.total%8}，得下卦${X.TRIGRAMS[r.meihua.original.lower].name}；除 6 余 ${r.meihua.total%6}，得第${r.meihua.moving}爻动（余 0 作 8 或 6）。</p><p><b>出生时间：</b>${escape(input.birthDate)} ${escape(input.unknownTime?'时辰不详':input.birthTime)}，${escape(input.birthZone)}。${r.birth.unknownTime?'遍历当天起止的时区换算范围，仅保留年、月柱一致的部分。':`换算固定 UTC+8 后为 ${r.birth.beijing}。`}${r.birth.ambiguous?'该当地时刻有两个可能的 UTC 时刻，本次采用较早者。':''} 四柱年界取立春，月界取节气，日界取午夜；沿用历法库晚子时的时干规则。未校正真太阳时。</p><p><b>解读规则：</b>所问类别为${{general:'万事',study:'学业',career:'事业',love:'情感',travel:'出行'}[r.reading.topic]}。小六壬落宫决定主意象，六壬第一课与梅花体用补充说明，出生五行提供行动比喻；不输出吉凶概率，不将卦象当作事实判断。</p>`;
    $('result').hidden=false;lastResult=r;
    const {birth,reading,...chart}=r;
    window.XuanqiLastCast={question:input.question.trim(),chart};
    window.dispatchEvent(new CustomEvent('xuanqi:cast'));
  }
  function submitInput(input){const r=X.calculate(input,new Date());render(r,input);error('');return r;}
  form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;const button=$('cast-button');try{button.disabled=true;const r=submitInput(getInput());$('result').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});$('result').focus({preventScroll:true});return r;}catch(e){error(e.message||'起课暂未完成，请核对输入后再试。');}finally{button.disabled=false;}});
  $('edit-question').addEventListener('click',()=>{$('divination').scrollIntoView({behavior:'smooth'});$('question').focus({preventScroll:true});});
  // Optional browser-native agent interface. All calculations use the same visible form action.
  const context=document.modelContext;
  if(context?.registerTool){const lifetime=new AbortController();window.addEventListener('pagehide',()=>lifetime.abort(),{once:true});try{Promise.resolve(context.registerTool({name:'cast_xuanqi_oracle',title:'玄契起课',description:'以当前北京时间起课，更新页面课象与文言、白话解读。仅供文化娱乐，问题和出生信息不上传或保存。',inputSchema:{type:'object',properties:{question:{type:'string',minLength:1,maxLength:300},topic:{type:'string',enum:['general','study','career','love','travel']},birthDate:{type:'string',description:'出生地公历日期 YYYY-MM-DD'},birthTime:{type:'string',description:'出生地当地时刻 HH:mm；unknownTime=true 时可留空'},birthPlace:{type:'string',minLength:1,maxLength:100},birthZone:{type:'string',description:'IANA 时区，如 Asia/Shanghai'},unknownTime:{type:'boolean'}},required:['question','topic','birthDate','birthPlace','birthZone','unknownTime'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){const r=X.calculate(input,new Date());$('question').value=input.question;$('character-count').textContent=`${input.question.length} / 300`;form.querySelectorAll('input[name=topic]').forEach(el=>el.checked=el.value===input.topic);$('birth-date').value=input.birthDate;$('birth-time').value=input.birthTime||'';$('unknown-time').checked=!!input.unknownTime;$('birth-time').disabled=!!input.unknownTime;$('birth-time').required=!input.unknownTime;$('birth-place').value=input.birthPlace;const hasZone=[...$('birth-zone').options].some(o=>o.value===input.birthZone);$('birth-zone').value=hasZone?input.birthZone:'custom';$('custom-zone').value=hasZone?'':input.birthZone;toggleCustom();render(r,input);error('');return {beijing:r.beijing,palace:r.small.name,hexagram:r.meihua.original.longName,classical:r.reading.classical,translation:r.reading.translation};}},{signal:lifetime.signal})).catch(()=>{});}catch{}}
})();
